using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Corspro.Domain
{
    /// <summary>
    /// Response is a class that helps the application to return all the messages and errors
    /// that were generated by running the process
    /// </summary>
    [DataContract]
    [Serializable]
    public class Response
    {
        /// <summary>
        /// Gets or sets the results.
        /// </summary>
        /// <value>
        /// The results.
        /// </value>
        [DataMember]
        public List<string> Results { get; set; }

        /// <summary>
        /// Gets or sets the errors.
        /// </summary>
        /// <value>
        /// The errors.
        /// </value>
        [DataMember]
        public List<string> Errors { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Response"/> class.
        /// </summary>
        public Response()
        {
            Results = new List<string>();
            Errors = new List<string>();
        }

    }
}
